### ISSUE TITLE
Jupyter kernel support

### ISSUE THREAD

**Issue by jasongrout** [StatTag/StatTag#1]
This looks like an interesting project! Have you considered adding Jupyter kernel support? This would open up executing the code in Python, Julia, C++, another way of communicating with R, and a host of [other languages](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels).

**Comment by jasongrout** [comment]
(I see you're in SF presenting at AMIA - I'm also in SF, happy to talk in person if it helps)

**Comment by lrasmus** [comment]
@jasongrout - would love to talk about this.  Admittedly we had not given this a lot of thought.  Sorry for not coordinating sooner - will send you an e-mail to see if we can coordinate a time to meet.  If not, maybe a conference call after we get back from conference?

**Comment by jasongrout** [comment]
Sounds great. I've been ill the last day or two, so unfortunately haven't been able to make it into the city. However, we can always chat on a conference call after the conference (I'm sure you're pretty busy now!)

**Comment by jasongrout** [comment]
I will be in SF on Friday, if you're still around then. Let's coordinate via email to see if a time then works for you.

**Comment by lrasmus** [comment]
Oooh, sorry to hear about not feeling well!  I'm in the same boat myself actually, and unfortunately am flying back today.  Sent an e-mail to start coordinating a time to set up a virtual meeting if we can.  Thanks again for being in touch!
