### ISSUE TITLE
Feature request: Support for Stata 17 customizable tables

### ISSUE THREAD

**Issue by mronkko** [StatTag/StatTag#18]
I am not sure if this is technically feasible, but it would be nice to have support for customizable tables (collect command) in Stata. 

https://www.stata.com/new-in-stata/tables/

**Comment by mronkko** [comment]
After posting, I realized that this might actually be already possible because collect export can export xlsx files. If this is possible, it would be nice to have this workflow explained in StatTag documentation.

**Comment by lrasmus** [comment]
Thank you @mronkko!  We'll do some testing to confirm this works, and absolutely can update this in the documentation.  Thanks so much for the request!

**Comment by lrasmus** [comment]
Great news, it looks like this works in a limited capacity with xlsx files (as noted by @mronkko).  Added a little more documentation about this - https://sites.northwestern.edu/stattag/2022/05/24/stata-17-and-custom-tables-with-collect/
