### ISSUE TITLE
Include XLSX files with R

### ISSUE THREAD

**Issue by jarathomas** [StatTag/StatTag#2]
Hello,

I think your project is very promising.  With respect to creating tables using R,
it seems we can include matrices, data frames, and lists, but is it possible to
include an excel file (xlsx)?  I'm no wizard with Word, but it seems that the R
packages for creating xlsx files would allow one to add additional formatting
to tables (so they are publication quality).

**Comment by lrasmus** [comment]
Thanks for the feedback @jarathomas!  Were you thinking to use XLSX output as a way to get the cells set up the way you want (more specific to string concatenation and what is in the cells), or to leverage the formatting (bolding, borders, etc.) within Excel?  Right now StatTag has ways to pull in data, but we are expecting all of the formatting to be done within Word.

**Comment by jarathomas** [comment]
Both.  If you ever need to make changes to the table content (i.e., actual numbers/stats) one
doesn't have to go through the formatting again (or some awkward copy and paste routine). Once
the formatting is set up for one table (with R code), then it is extremely simple to use the same
formatting for subsequent tables (or tables in a different paper).

Thanks for getting back to me so quickly.

**Comment by lrasmus** [comment]
Fortunately, if you do the formatting in Word, when you update the table with new results that will all be preserved.  Glad this was helpful - we have had people ask about importing visually formatted tables, so I'll open a linked issue just to track the request.
